; PlatformIO Project Configuration File

[platformio]
boards_dir = ./board
default_envs = T-QT-Pro-N4R2
src_dir = src

[env:T-QT-Pro-N4R2]
platform = espressif32@6.12.0
board = esp32-s3-t-qt-pro
framework = arduino
monitor_speed = 115200

build_flags =

board_build.filesystem = littlefs

lib_deps =
    mathieucarbou/ESPAsyncWebServer@^3.6.0
    mathieucarbou/AsyncTCP@^3.3.2